[book]
title = "Open Quantum Computing Textbook"
description = "An open textbook for quantum computing theory and its applications."
author = "Daniel Park"
language = "eng"
multilingual = false
src = "source"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"

[preprocessor.katex]
after = ["links"]
