[book]
title = "Open Quantum Computing Textbook"
description = "An open textbook for quantum computing theory and its applications."
authors = ["Daniel Park"]
language = "eng"
src = "source"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
additional-css = ["langtabs.css", "custom.css"]
additional-js = ["langtabs.js"]

[preprocessor.katex]
after = ["links"]

[preprocessor.langtabs]
command = "mdbook-langtabs"
